services:
  markdown-redirect-server:
    container_name: "markdown-redirect-server"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - .:/app
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - $HOME/markdown-link-redirect/gin_blocked.log:/var/log/gin_blocked.log
    environment:
      - GIN_MODE=$GIN_MODE

  # If you need a database, you can uncomment and configure this service
  # db:
  #   image: postgres:13
  #   environment:
  #     - POSTGRES_DB=myapp
  #     - POSTGRES_USER=user
  #     - POSTGRES_PASSWORD=password
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data

# Uncomment if using a database
# volumes:
#   postgres_data:
